### PR TITLE
Support online atcoder contest

### PR DESCRIPTION
**Pull request by shanto86**
Please let me know if you have any suggestion. Thanks

### CODE REVIEW

**Comment by dj3500** [comment]
Wow, this commit is big. Awesome!

A few requests/questions:
1. It seems that NetBeans inserted some absolute paths in the project.properties file, which means that now the project only compiles on your computer.
2. Please rebase on the newest version (i.e. the one after #98 was merged in). (Maybe this is not needed if you implement point 5.)
3. Do we really need all of these libraries? Now the executable file grows from 0.7 MB to 10 MB. It's not the end of the world, but...
4. How can one test this? Are there any contests on AtCoder (except currently-running short contests) where login is required to see the problems?
5. I'm not a big fan of lugging this AuthenticationInfo object around in a lot of calls (schedule(), getProblemURLListFromURL() etc.) even for parsers other than AtCoder, which do not require authentication. Maybe we could instead modify the Config object to store the username and password on a transient basis (i.e. without storing them on disk). Going forward, I think it would actually be good to have an option to store these in the config file.
6. I think we should add build-impl.xml to .gitignore, it seems to be a generated file (this is not really related to this pull request...)
7. Does the task parser still work if the user pastes a URL like "http://agc003.contest.atcoder.jp/assignments"?

I didn't run the code yet, so I might have more comments once I do. Again, thanks a lot for so much effort!

**Comment by shanto86** [comment]
Hi, Sorry for the late reply. Response inlined.

On Sat, Feb 4, 2017 at 8:58 PM, dj3500 <notifications@github.com> wrote:

> Wow, this commit is big. Awesome!
>
> A few requests/questions:
>
>    1. It seems that NetBeans inserted some absolute paths in the
>    project.properties file, which means that now the project only compiles on
>    your computer.
>
> Ah sorry, I tried to look for such error, but somehow it slipped through.
I will have a look.

>
>    1. Please rebase on the newest version (i.e. the one after #98
>    <https://github.com/dj3500/hightail/pull/98> was merged in). (Maybe
>    this is not needed if you implement point 5.)
>    2. Do we really need all of these libraries? Now the executable file
>    grows from 0.7 MB to 10 MB. It's not the end of the world, but...
>
> Yes, I was also taken back when I saw such huge increase in jar size. But
without some of them it does not build. Although it's true that I did not
check individually all of them, but initially I added them in increment
basis and then I needed to add almost 8-10 manually. Later I found some
website which was giving all the necessary libs for htmlunit.

>
>    1. How can one test this? Are there any contests on AtCoder (except
>    currently-running short contests) where login is required to see the
>    problems?
>
> I tested with practice contest at AtCoder. The problem is, once you press
the "Join The Contest" Button it will never appear. So you can test "click
the button" part only once (or in some online contest). Otherwise, you can
try logging in in practice contest as well.

>
>    1. I'm not a big fan of lugging this AuthenticationInfo object around
>    in a lot of calls (schedule(), getProblemURLListFromURL() etc.) even for
>    parsers other than AtCoder, which do not require authentication. Maybe we
>    could instead modify the Config object to store the username and password
>    on a transient basis (i.e. without storing them on disk). Going forward, I
>    think it would actually be good to have an option to store these in the
>    config file.
>
> Yah that's a good idea (keeping id/pw in transient basis at Config class).
However, I am not sure how do you want to store those in config file. Since
config file is a plain text, any one can see the id/pw right? Also if you
want to encrypt it the code is open, so any ill intended person can steal
it. Do you have any better plan?

>
>    1. I think we should add build-impl.xml to .gitignore, it seems to be
>    a generated file (this is not really related to this pull request...)
>
> Okay will have a look.

>
>    1. Does the task parser still work if the user pastes a URL like "
>    http://agc003.contest.atcoder.jp/assignments
>    <http://agc003.contest.atcoder.jp/assignments>"?
>
> Not sure, I will have a look.

>
>
> I didn't run the code yet, so I might have more comments once I do. Again,
> thanks a lot for so much effort!
>
> —
>
No problem, it will take some time to accommodate all the requests. Let's
see how soon I can fix them.

Thanks,

**Comment by dj3500** [comment]
About the size: when I download HTMLUnit, the zip file is already like 13 MB, so maybe it's just impossible to thin this down significantly. Still, it's not a disaster.

For the logins: yeah, if the user wants to store them, then we just store them in the config file (maybe we can have some simple two-way encryption so that it's not possible to know the password by just looking over someone's shoulder when the config file is open). We should warn the user.

As an ideal solution, I would probably see the following: we put the username/password prompt both in the config panel and in the New Contest panel. In the New Contest panel, the fields should be already filled-in if they are available in the Config object (either from the config file, or from already having been filled-in in this execution of Hightail). Maybe a "Remember credentials" checkbox as well in the New Contest panel (which would store them permanently in the config file).

Thanks again!

**Comment by dj3500** [comment]
Also, the parsing fails (or rather gets stuck) for http://practice.contest.atcoder.jp/ (maybe due to Japanese characters in the problem name).

**Comment by shanto86** [comment]
are you sure? it works for me at least.

**Comment by shanto86** [comment]
Addressed all your comments.

One thing, http://agc003.contest.atcoder.jp/assignments does not work. You need to provide "http://agc003.contest.atcoder.jp" or "https://agc003.contest.atcoder.jp" (trailing / is optional).

I tested "new task" and it works as well, even if you do not provide id/pw. However, since there is no option of id/pw while "new task"ing, so online contest tasks can not be parsed in this way.

**Comment by dj3500** [comment]
Hi,

As you can see, I've merged the pull request. A few more comments:

(a) About practice non-working: I edited my post above, but I guess you only got the non-edited version in the email. Indeed it works.
(b) I made an easy change to also allow URLs with "assignments" - take a look and tell me if it's fine.
(c) There was a bug where if you tried to parse two different contests within the same run of Hightail, it errored out. I made it create a new webClient object every time a contest starts parsing, and that seems to have fixed it.
(d) I added a few tests (one for task parsing and four for contest parsing).
(e) I redesigned the New Contest dialog and removed all changed from the New Problem dialog.

Again, many thanks for the contribution!

**Comment by shanto86** [comment]
nice, thanks. i will give it a try at next atcoder contest.

**Comment by dj3500** [comment]
It actually has never worked for scheduling contests, at least since you refactored the lugging-around AuthenticationInfo thing on my request :P This is because the login+password was never saved anywhere if the user only clicked on "Add contest" (see a0fa89). Now it should work...

**Pull request merged**
