### PR TITLE
#68 Bug Fix

### PR DESCRIPTION
**Pull request by Mketa**
Made the text areas' width resizable. Now when the window size changes, the text areas' change as well.

//This is my first time using git, so forgive any thing I may have done wrong.

### CODE REVIEW

**Comment by dj3500** [comment]
Why did you close this? :)

**Comment by Mketa** [comment]
Apparently, I had put only one of the text areas to autoresize, I guess I will redo it now, hopefully correct this time :)

**Comment by dj3500** [comment]
I wonder if it wouldn't be best to only resize the output field. The use case of making the window larger that I can see is mostly wanting to better see the tons of debug output that our program produced.

**Comment by Mketa** [comment]
I guess it sounds plausible to only have one of them to resize. But sometimes, when we are checking the program and the correct output side by side, we need to have some equal space for both.
image 
Anyway I will recheck the code and re-pull after 10 minutes :) Thanks

**Pull request closed without merging**
