### PR TITLE
Add HTTPServer

### PR DESCRIPTION
**Pull request by jmerle**
I've recently been putting time in extending my own CHelper-compatible extension so that it works with other tools aswell. More information about that can be found [here](https://github.com/jmerle/chelper-companion/issues/3). At the moment the extension (on the feature/universal branch) has 21 problem parsers and 13 contest parsers (the supported websites are listed [here](https://github.com/jmerle/chelper-companion/blob/feature/universal/README.md)).

I've added the necessary functionality to Hightail so that it can receive problem data via HTTP POST requests, which my extension can send to a running Hightail instance. I have added the [org.json](https://mvnrepository.com/artifact/org.json/json/20180130) library to parse the JSON data that is sent by my extension.

Here is a little demo: [YouTube](https://www.youtube.com/watch?v=LnI4HuzWY18).

### CODE REVIEW

**Comment by dj3500** [comment]
Extremely interesting! Please give me a longer while to review it though, I'm a bit short on time these days. :)

**Comment by jmerle** [comment]
No worries, there's no deadline to this :)

**Comment by jmerle** [comment]
The latest commit adds a link to the extension in the project's readme and brings the window to the front when a problem or a contest is parsed.

If you want to try it yourself, install the extension for [Chrome](https://chrome.google.com/webstore/detail/competitive-companion/cjnmckjndlpiamhfimnnjmnckgghkjbl) or [Firefox](https://addons.mozilla.org/en-US/firefox/addon/competitive-companion/), run the project from my fork and go to a problem page like [this](http://codeforces.com/problemset/problem/954/G) one. In Chrome the little plus icon should go green and on Firefox a green plus button will be added to the top-right of the url bar. Just click on it and see the magic happen.

**Comment by jmerle** [comment]
Some weeks has passed, do you have an estimate of when you might have some time to look at it?

**Comment by dj3500** [comment]
I made a new release with this functionality, including some comments in README, About dialog, and a pop-up at the beginning. Also made it only listen to localhost (for security reasons and to suppress a prompt from the Windows Firewall).

Thanks again!

**Pull request merged**
